set(EDGE_AGENT_PROJECT_LOG_PREFIX "[edge_agent]")
set(EDGE_AGENT_FLASH_SIZE "")
set(EDGE_AGENT_BOARD_MANAGER_DEFAULTS "${CMAKE_SOURCE_DIR}/components/gen_bmgr_codes/board_manager.defaults")

# Build the base SDKCONFIG_DEFAULTS chain (later files win over earlier ones).
if(SDKCONFIG_DEFAULTS)
    set(EDGE_AGENT_SDKCONFIG_DEFAULTS_CHAIN "${SDKCONFIG_DEFAULTS}")
elseif(NOT "$ENV{SDKCONFIG_DEFAULTS}" STREQUAL "")
    set(EDGE_AGENT_SDKCONFIG_DEFAULTS_CHAIN "$ENV{SDKCONFIG_DEFAULTS}")
else()
    set(EDGE_AGENT_SDKCONFIG_DEFAULTS_CHAIN "${CMAKE_SOURCE_DIR}/sdkconfig.defaults")
endif()

# Apply the board-specific defaults generated by `idf.py gen-bmgr-config`.
# board_manager.defaults carries the selected board's hardware configuration
# (PSRAM, flash size/mode, CPU frequency, peripheral support, partition table).
# Without including it in the defaults chain these settings are never applied,
# so the persisted sdkconfig silently drifts after a target switch (e.g. PSRAM
# turns off -> CONFIG_SPIRAM missing -> every MALLOC_CAP_SPIRAM allocation
# fails with ESP_ERR_NO_MEM). This is board-agnostic: each board generates its
# own board_manager.defaults, so the correct settings are applied per board.
if(EXISTS "${EDGE_AGENT_BOARD_MANAGER_DEFAULTS}")
    list(APPEND EDGE_AGENT_SDKCONFIG_DEFAULTS_CHAIN "${EDGE_AGENT_BOARD_MANAGER_DEFAULTS}")

    file(STRINGS "${EDGE_AGENT_BOARD_MANAGER_DEFAULTS}" _flash_line REGEX "^CONFIG_ESPTOOLPY_FLASHSIZE_(4|8|16|32)MB=y$")
    if(_flash_line)
        list(GET _flash_line 0 _flash_line)
        string(REGEX REPLACE "^CONFIG_ESPTOOLPY_FLASHSIZE_((4|8|16|32)MB)=y$" "\\1" EDGE_AGENT_FLASH_SIZE "${_flash_line}")
    endif()
endif()

if(EDGE_AGENT_FLASH_SIZE)
    if(EXISTS "${CMAKE_SOURCE_DIR}/sdkconfig")
        file(READ "${CMAKE_SOURCE_DIR}/sdkconfig" EDGE_AGENT_SDKCONFIG_CONTENT)
        string(REGEX REPLACE "(^|\\n)CONFIG_PARTITION_TABLE_CUSTOM_FILENAME=\"[^\\n]*\"\\n" "\\1" EDGE_AGENT_SDKCONFIG_CONTENT "${EDGE_AGENT_SDKCONFIG_CONTENT}")
        string(REGEX REPLACE "(^|\\n)CONFIG_PARTITION_TABLE_FILENAME=\"[^\\n]*\"\\n" "\\1" EDGE_AGENT_SDKCONFIG_CONTENT "${EDGE_AGENT_SDKCONFIG_CONTENT}")
        file(WRITE "${CMAKE_SOURCE_DIR}/sdkconfig" "${EDGE_AGENT_SDKCONFIG_CONTENT}")
    endif()

    set(EDGE_AGENT_PARTITION_DEFAULTS "${CMAKE_BINARY_DIR}/edge_agent_partition_auto.defaults")
    file(WRITE "${EDGE_AGENT_PARTITION_DEFAULTS}"
        "# Auto-generated from flash size selection. Do not edit.\n"
        "CONFIG_PARTITION_TABLE_CUSTOM=y\n"
        "CONFIG_PARTITION_TABLE_CUSTOM_FILENAME=\"partitions_${EDGE_AGENT_FLASH_SIZE}.csv\"\n")

    list(APPEND EDGE_AGENT_SDKCONFIG_DEFAULTS_CHAIN "${EDGE_AGENT_PARTITION_DEFAULTS}")

    message(STATUS "${EDGE_AGENT_PROJECT_LOG_PREFIX} Partition table auto-selected: partitions_${EDGE_AGENT_FLASH_SIZE}.csv")
endif()

set(SDKCONFIG_DEFAULTS "${EDGE_AGENT_SDKCONFIG_DEFAULTS_CHAIN}")
